CREATE TABLE utenteType (
    id_utenteType INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeUtenteType VARCHAR(128)
);


CREATE TABLE postType (
    id_postType INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipologia VARCHAR(128)
);


CREATE TABLE utentiRegistrati (
    personalID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeUtente VARCHAR(128),
    cognomeUtente VARCHAR(128),
    url VARCHAR(128),
    biografia VARCHAR (256),
    dataNascita VARCHAR(20),
    password VARCHAR(128),
    UtenteType INTEGER,
    FOREIGN KEY (UtenteType) REFERENCES utenteType(id_utenteType)
);


CREATE TABLE Posts (
    id_post INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente INTEGER,
    FOREIGN KEY (utente) REFERENCES utentiRegistrati(personalID) ON DELETE CASCADE,
    content VARCHAR(256),
    postType INTEGER,
    idUtenteBacheca INTEGER,
    FOREIGN KEY (postType) REFERENCES postType(id_postType),
    FOREIGN KEY (idUtenteBacheca) REFERENCES utentiRegistrati(personalID) ON DELETE CASCADE,
    allegato VARCHAR(256)
);

CREATE TABLE gruppi (
    id_gruppi INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeGroup VARCHAR(256),
    idUtenteProprietario INTEGER,
    FOREIGN KEY (idUtenteProprietario) REFERENCES utentiRegistrati(personalID) ON DELETE CASCADE
);


CREATE TABLE listaUtentiGroup (
    id_listaUtenti INTEGER,
    utenteGroup INTEGER,
    FOREIGN KEY (id_listaUtenti) REFERENCES gruppi(id_gruppi) ON DELETE CASCADE,
    FOREIGN KEY (utenteGroup) REFERENCES utentiRegistrati(personalID) ON DELETE CASCADE,
    PRIMARY KEY (id_listaUtenti, utenteGroup)
);


CREATE TABLE amicizie (
    utente1 INTEGER,
    utente2 INTEGER,
    FOREIGN KEY (utente1) REFERENCES utentiRegistrati(personalID) ON DELETE CASCADE,
    FOREIGN KEY (utente2) REFERENCES utentiRegistrati(personalID) ON DELETE CASCADE,
    PRIMARY KEY (utente1, utente2)
);


--popolamento tabella utentiTipologia 
INSERT INTO utenteType (id_utenteType, nomeUtenteType)
VALUES (default, 'AMM');


INSERT INTO utenteType (id_utenteType, nomeUtenteType)
VALUES (default, 'NORMAL');


--popolamento tabella utenti
INSERT INTO utentiRegistrati (personalID, nomeUtente, cognomeUtente, url, biografia, dataNascita, password, UtenteType)
VALUES (default, 'amministratore', 'amministratore', '', 'amministratore del sito','29-JUN-04', 'amministratore', 1);

--popolamento tabella utenti
INSERT INTO utentiRegistrati (personalID, nomeUtente, cognomeUtente, url, biografia, dataNascita, password, UtenteType)
VALUES (default, 'Mark', 'Zuckerberg', 'img/Mark.jpg', 'fondatore','29-JUN-04', 'Mark', 2);

--popolamento tabella utenti
INSERT INTO utentiRegistrati (personalID, nomeUtente, cognomeUtente, url, biografia, dataNascita, password, UtenteType)
VALUES (default, 'Hack', 'Rino', 'img/picHacherino.jpg', 'Hacker di fama mondiale','29-JUN-04', 'Hack', 2);

--popolamento tabella utenti
INSERT INTO utentiRegistrati (personalID, nomeUtente, cognomeUtente, url, biografia, dataNascita, password, UtenteType)
VALUES (default, 'Jon', 'Sudano', 'img/jonsudano.jpg', 'cantante','29-JUN-04', 'Jon', 2);

--popolamento postType
INSERT INTO postType (id_postType, tipologia)
VALUES (default, 'POST_TESTO');

INSERT INTO postType (id_postType, tipologia)
VALUES (default, 'POST_IMMAGINE');

--popolamento posts
INSERT INTO Posts (id_post, utente, content, postType , idUtenteBacheca, allegato)
VALUES (default,
         2,
         'Fiamma! Oggi prima lezione diPR1. Solo bomba!', 
        1,
         2,
         '');

--popolamento posts
INSERT INTO Posts (id_post, utente, content, postType , idUtenteBacheca, allegato)
VALUES (default,
         3,
         'Ci stanno tracciando, staccaaaaaaaa', 
        2, 
        3,
         'img/imhacherino.jpg');

--popolamento posts
INSERT INTO Posts (id_post, utente, content, postType , idUtenteBacheca, allegato)
VALUES (default,
         4, 
        'Follow me and see a new video on Youtube!', 
        1, 
        4,
         'https://www.youtube.com/watch?v=gTwxtYin1p0');

--popolamento gruppi e lista utenti gruppi
INSERT INTO gruppi (id_gruppi, nomeGroup, idUtenteProprietario)
VALUES (default, 'Chi stava guardando la melevisione l undici settembre', 2);

INSERT INTO gruppi (id_gruppi, nomeGroup, idUtenteProprietario)
VALUES (default, 'X chi vuole partire a Milano per Natale', 2);

INSERT INTO gruppi (id_gruppi, nomeGroup, idUtenteProprietario)
VALUES (default, 'Quelli del palazzo delle scienze', 3);

INSERT INTO listaUtentiGroup (id_listaUtenti, utenteGroup)
VALUES
(1, 2),
(1, 3),
(1, 4),
(2, 2),
(2, 3),
(3, 4),
(2, 4);

---popolamento amicizie
INSERT INTO amicizie (utente1, utente2)
VALUES
(2,3),
(3,2),
(2,4),
(4,2),
(3,4),
(4,3);